language: node_js
node_js:
  - "6"
  
script:
  - npm install
  - node_modules/.bin/gitbook install
  - node_modules/.bin/gitbook build
  - node_modules/.bin/surge --domain http://cloudmigration-courseware.surge.sh/ --project ./_book